[package]
name = "proto-awscli"
version = "1.2.0-alpha.20260908.3"
edition = "2024"
description = "Proto WASM plugin for AWS CLI v2."
authors = ["ageha734"]
license = "MIT"
repository = "https://github.com/ageha734/proto-awscli"
publish = false

[features]
default = []
wasm = []

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.4.1"
proto_pdk = "0.35.3"

[dev-dependencies]
proto_pdk_test_utils = "0.50.0"
starbase_sandbox = "0.12.0"
tokio = { version = "1", features = ["full"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
